name: Build and Push Docker Image

# This workflow should only be run manually when we need to update the build environment
# It builds and pushes a Docker image with all necessary dependencies for Flutter Android builds
on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for building the image'
        required: true
        default: 'Update build environment'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/magpern/bikebleflutter:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max 