name: Flutter CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      # Optional: upgrade dependencies
      - name: Upgrade dependencies
        run: flutter pub upgrade

      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run tests
      - name: Run tests
        run: flutter test

      # Extract app version from pubspec.yaml
      - name: Get version
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d' ' -f2)
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Build AAB for Play Store
      - name: Build app bundle (AAB)
        run: flutter build appbundle --release

      # Rename AAB file
      - name: Rename AAB
        run: |
          mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/BikeBLE_Config-${{ steps.version.outputs.version }}.aab

      # Upload AAB as an artifact
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/BikeBLE_Config-${{ steps.version.outputs.version }}.aab

  deploy:
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # Extract version again (for renaming)
      - name: Get version
        id: version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d' ' -f2)
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Download previously built AAB artifact
      - name: Download AAB artifact
        uses: actions/download-artifact@v3
        with:
          name: release-aab

      # Upload to Google Play Store
      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON }}
          packageName: se.casaperne.BikeBLE_scanner
          releaseFiles: BikeBLE_Config-${{ steps.version.outputs.version }}.aab
          track: production
          status: completed
